# fly.toml app configuration file generated for librefit-web on 2024-03-10T10:26:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'librefit-web'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.ports]]
  handlers = ["http"]
  port = 3000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
