name: Feature Request
description: Suggest a new feature or enhancement for LibreFit
title: "[Feature]: "
labels: ["enhancement", "review required"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your idea.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which area does this feature relate to?
      options:
        - Dashboard
        - Calorie Tracking
        - Weight Tracking
        - History View
        - Progress/Charts
        - Setup Wizard
        - Settings
        - Data Export
        - New Feature
    validations:
      required: true

  - type: dropdown
    id: target
    attributes:
      label: Target Platform
      description: Which platform(s) should this feature be available on?
      options:
        - Android
        - iOS
        - Common (both platforms)
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added or improved?
      placeholder: I would like to have...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution / Mockup
      description: How do you envision this working? Include mockups, sketches, or examples if possible.
      placeholder: |
        This could work by...

        (You can drag and drop images here)
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement (Optional)
      description: What problem does this feature solve?
      placeholder: Currently, users cannot...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered (Optional)
      description: Have you thought of any alternative solutions or workarounds?
      placeholder: I also considered...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...
