version: '3.8'
networks:
  librefit-network:
    driver: bridge

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    hostname: librefit-db
    container_name: librefit-db
    environment:
      - POSTGRES_USER=librefit
      - POSTGRES_PASSWORD=librefit
      - POSTGRES_DB=dev
    ports:
      - '5432:5432'
    networks:
      - librefit-network

  service:
    image: librefit-service:latest
    restart: always
    hostname: librefit-service
    container_name: librefit-service
    environment:
      - POSTGRES_USER=librefit
      - POSTGRES_PASSWORD=librefit
      - POSTGRES_HOST=librefit-db
      - POSTGRES_DB=dev
    ports:
      - '8080:8080'
    networks:
      - librefit-network

  web:
    image: librefit-web:latest
    container_name: librefit-web
    restart: always
    ports:
      - '3000:3000'
    networks:
      - librefit-network