version: '3.8'
networks:
  librefit-network:
    driver: bridge

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    hostname: librefit-db
    container_name: librefit-db
    environment:
      - POSTGRES_USER=librefit
      - POSTGRES_PASSWORD=librefit
      - POSTGRES_DB=librefit
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U librefit" ]
        interval: 5s
        timeout: 5s
        retries: 6
    ports:
      - '5432:5432'
    networks:
      - librefit-network

  service:
    image: librefit-service:latest
    restart: always
    hostname: librefit-service
    container_name: librefit-service
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://librefit-db:5432/librefit
      QUARKUS_DATASOURCE_USERNAME: librefit
      QUARKUS_DATASOURCE_PASSWORD: librefit
    ports:
      - '8080:8080'
    networks:
      - librefit-network
    depends_on:
      db:
        condition: service_healthy

  #web:
  #  image: librefit-web:latest
  #  container_name: librefit-web
  #  hostname: librefit-web
  #  restart: always
  #  environment:
  #    - ORIGIN=http://localhost:3000
  #    - API_BASE_PATH=http://librefit-service:8080
  #  ports:
  #    - '3000:3000'
  #  networks:
  #    - librefit-network